version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: rm -f package-lock.json && npm install
            - run: npm install jest-expo
            - run: sudo npm install -g expo-cli
            - run: npm ci
            - run: npx jest --ci

workflows:
  build-and-test:
    jobs:
      - build-and-test
