- run:
  name: Setting up dependences
  command: npm install -g npm@latest
  command: npm install
  command: npm install jest-expo
  command: npm install -g expo-cli
- run:
  name: Run test
  command: npm ci
  command: npx jest --ci
- run:
 name: Login into Expo
 command: npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
- run:
 name: Save current branch name to an env variable
 command: |
   if [ "${CIRCLE_BRANCH}" == "master" ]; then
     echo 'export EXPO_RELEASE_CHANNEL="default"' >> $BASH_ENV
   else
     echo 'export EXPO_RELEASE_CHANNEL=$CIRCLE_BRANCH' >> $BASH_ENV
   fi
- run:
 name: Publish to Expo
 command: npx expo publish --non-interactive --max-workers 1 -- release-channel $EXPO_RELEASE_CHANNEL
